import type { IShipmentCreate } from "@models/shipment.schema";

/**
 * Sample shipment data for grid, tile, and report views.
 */
export const SAMPLE_SHIPMENTS: IShipmentCreate[] = [
  {
    shipperName: "Acme Logistics",
    carrierName: "FastFreight Inc",
    pickupLocation: "123 Warehouse Ave, Chicago, IL",
    deliveryLocation: "456 Commerce St, Dallas, TX",
    trackingNumber: "TRK001234567",
    status: "in_transit",
    rate: 1250.5,
  },
  {
    shipperName: "Global Supplies Co",
    carrierName: "Pacific Haulers",
    pickupLocation: "789 Port Rd, Los Angeles, CA",
    deliveryLocation: "321 Industrial Blvd, Seattle, WA",
    trackingNumber: "TRK002345678",
    status: "delivered",
    rate: 890.0,
  },
  {
    shipperName: "Metro Retail Group",
    carrierName: "Eastern Express",
    pickupLocation: "555 Distribution Dr, Atlanta, GA",
    deliveryLocation: "777 Mall Way, Miami, FL",
    trackingNumber: null,
    status: "pending",
    rate: 2100.75,
  },
  {
    shipperName: "TechParts Ltd",
    carrierName: "QuickShip Logistics",
    pickupLocation: "100 Tech Park, Austin, TX",
    deliveryLocation: "200 Innovation Ave, Boston, MA",
    trackingNumber: "TRK003456789",
    status: "in_transit",
    rate: 675.25,
  },
  {
    shipperName: "Fresh Foods Distribution",
    carrierName: "ColdChain Transport",
    pickupLocation: "400 Farm Rd, Fresno, CA",
    deliveryLocation: "600 Market St, Phoenix, AZ",
    trackingNumber: "TRK004567890",
    status: "in_transit",
    rate: 450.0,
  },
  {
    shipperName: "BuildRight Materials",
    carrierName: "HeavyLoad Freight",
    pickupLocation: "800 Quarry Ln, Denver, CO",
    deliveryLocation: "900 Construction Way, Las Vegas, NV",
    trackingNumber: "TRK005678901",
    status: "pending",
    rate: 3200.0,
  },
  {
    shipperName: "Style Fashion Co",
    carrierName: "Fashion Express",
    pickupLocation: "110 Design St, New York, NY",
    deliveryLocation: "220 Retail Blvd, San Francisco, CA",
    trackingNumber: "TRK006789012",
    status: "delivered",
    rate: 1580.5,
  },
  {
    shipperName: "MedSupply Corp",
    carrierName: "Urgent Cargo",
    pickupLocation: "330 Medical Dr, Philadelphia, PA",
    deliveryLocation: "440 Hospital Way, Detroit, MI",
    trackingNumber: null,
    status: "in_transit",
    rate: 920.0,
  },
  {
    shipperName: "AutoParts Direct",
    carrierName: "Wheels & Freight",
    pickupLocation: "550 Garage Rd, Detroit, MI",
    deliveryLocation: "660 Mechanic St, Cleveland, OH",
    trackingNumber: "TRK007890123",
    status: "delivered",
    rate: 540.25,
  },
  {
    shipperName: "Office Essentials",
    carrierName: "Desk Delivery",
    pickupLocation: "770 Business Park, Minneapolis, MN",
    deliveryLocation: "880 Corporate Ave, Chicago, IL",
    trackingNumber: "TRK008901234",
    status: "pending",
    rate: 380.0,
  },
];
